name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: build GO
      run: cd go && go build -v ./...
      
    - name: build Rust
      run: cd rust && cargo build --verbose
