name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: build Go
      run: cd go && go build *.go

    - name: cache rust
      uses: Swatinem/rust-cache@v1.3.0

    - name: build Rust
      run: cd rust && cargo build --verbose

    - name: start Rust server
      run: RUST_LOG=debug ./rust/target/debug/rust &

    - name: start Go server
      run: cd go && ls -la && ./main  &

    - name: install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: run test
      run: npm ci && npm test
